### ISSUE TITLE
Resources - Neural networks, from zero to hero

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFrLab/ssphub#42]
En attendant #37 je pousse ici la référence vers le site assez jeune de Karpathy pour son cycle de formation sur les réseaux de neurones : https://karpathy.ai/zero-to-hero.html

**Comment by linogaliana** [comment]
- Merci @romaintailhurat pour la proposition, je ne connaissais pas, ça a l'air super. J'ai fait service minimum pour l'intégration de le site _web_ pour limiter le poids de la maintenance

- Je propose dans #44 d'intégrer ça dans les ressources listées. Si le [_preview_](https://deploy-preview-44--ssphub.netlify.app/courses/) te semble ok, je valide

**Comment by romaintailhurat** [comment]
@linogaliana c'est parfait, merci !
