### ISSUE TITLE
Feature request: add RSS feed to your blog

### ISSUE THREAD

**Issue by aborruso** [InseeFrLab/ssphub#78]
You publish great content: if you enable QUARTO RSS feeds, it is much easier to follow you.

Thank you and congratulations for what you do

**Comment by linogaliana** [comment]
Hi thanks for the idea ! I will implement that soon, should not be complicated

**Comment by aborruso** [comment]
Thank you very much @linogaliana for this 
https://ssphub.netlify.app/index.xml
